In [1]:
import tensorflow as tf
import numpy as np

sess = tf.Session()

# Tensor, Variable, Operation

These are the three basic building blocks of computation graphs in tensorflow

# Tensor

Initialize a session and a tensor **tr**

In [2]:
tr = tf.random_normal([2, 3], -2., 2.) # Definition, Tensor

In [3]:
# print out shape of Tensor
tr.get_shape()

TensorShape([Dimension(2), Dimension(3)])

**tf**, when initialized, is only part of the computation graph. It won't be evaluated until the operations in the graph are executed.

In [4]:
print tr.eval(session=sess) # Action
# or equivalently
print sess.run(tr) # Action

[[ 0.2762928  -2.69166422 -3.40478659]
 [-2.78476477 -4.56543303 -2.75076532]]
[[-3.32669592  0.24397206 -3.84729671]
 [ 0.21123004  1.46784687 -0.95309842]]


# Variable

Initial value of an Variable **e**

In [5]:
e = tf.Variable(np.exp(1), expected_shape=[], dtype=tf.float64) # Definition, Variable

Before call **sess.run()** or **Variable.eval()**, we must perform the **Operation** that actually initializes **e** using the provided initial value.

In [6]:
init = tf.global_variables_initializer() # Definition, Variable
sess.run(init) # Action
# Or equivalently
sess.run(e.initializer) # Action

In [7]:
# Variable.initial_value is a tensor
tr = e.initial_value 
# Use this when initial value of Var1 is dependent on another variable Var2

In [8]:
print e.eval(session=sess) # Action
# or equivalently
print sess.run(e) # Action

2.71828182846
2.71828182846


In [9]:
# print out the shape of Variable 
e.get_shape()

TensorShape([])

Concrete example from https://www.tensorflow.org/get_started/

In [10]:
# Create dataset
x_data = np.random.rand(100).astype(np.float32)
y_data = x_data * 0.1 + 0.3

W = tf.Variable(tf.random_uniform([1], -1.0, 1.0)) # Definition, Varialbe
b = tf.Variable(tf.zeros([1])) # Definition, Varialbe
y = W * x_data + b # Definition, Tensor

loss = tf.reduce_mean(tf.square(y - y_data)) # Definition, Tensor
optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss) # Definition, Operation

init = tf.global_variables_initializer() # Definition, Operation

sess = tf.Session()
sess.run(init) # Actually performs the initialization Operation on (`W` and `b`)

"""
Given the objective function `loss` (a Tensor) and the initialized Variables (`W` and `b`),
the next step is to repeatedly perform the `train` Operation that minimize
`loss` using GradientDecent
""" 

for step in range(201):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(W), sess.run(b)) # Dump the value of trained parameters


(0, array([-0.06282353], dtype=float32), array([ 0.5302766], dtype=float32))
(20, array([ 0.04523178], dtype=float32), array([ 0.3290838], dtype=float32))
(40, array([ 0.08651239], dtype=float32), array([ 0.30716237], dtype=float32))
(60, array([ 0.09667846], dtype=float32), array([ 0.30176386], dtype=float32))
(80, array([ 0.09918202], dtype=float32), array([ 0.30043438], dtype=float32))
(100, array([ 0.09979857], dtype=float32), array([ 0.30010697], dtype=float32))
(120, array([ 0.0999504], dtype=float32), array([ 0.30002636], dtype=float32))
(140, array([ 0.0999878], dtype=float32), array([ 0.30000648], dtype=float32))
(160, array([ 0.09999698], dtype=float32), array([ 0.30000162], dtype=float32))
(180, array([ 0.09999925], dtype=float32), array([ 0.30000043], dtype=float32))
(200, array([ 0.09999981], dtype=float32), array([ 0.3000001], dtype=float32))


In [11]:
sess.close()